./5-mysql_backup

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -1,30 +1,39 @@
 #!/usr/bin/env bash
-
-# Check if the password argument is provided
-if [ -z "$1" ]; then
-  echo "Usage: $0 <mysql_root_password>"
-  exit 1
-fi
-
-# Create a MySQL dump of all databases named backup.sql
+# Does the following:
+#	- creates a mysql dump of all MySQL dbs named backup.sql
+#	- compresses the dump file to tar.gz archive
+#	- name format: day-month-year.tar.gz
 sudo mysqldump --user=root --password="$1" --all-databases > backup.sql
-
-# Check if the dump was successful
-if [ $? -ne 0 ]; then
-  echo "MySQL dump failed!"
-  exit 1
-fi
-
-# Compress the dump file to a tar.gz archive with the format day-month-year.tar.gz
 tar -cvzf "$(date +"%d-%m-%Y").tar.gz" backup.sql
 
-# Check if the compression was successful
-if [ $? -ne 0 ]; then
-  echo "Compression failed!"
-  exit 1
-fi
 
-# Remove the original dump file to save space
-rm backup.sql
+# #!/usr/bin/env bash
 
-echo "Backup and compression completed successfully."
+# # Check if the password argument is provided
+# if [ -z "$1" ]; then
+#   echo "Usage: $0 <mysql_root_password>"
+#   exit 1
+# fi
+
+# # Create a MySQL dump of all databases named backup.sql
+# sudo mysqldump --user=root --password="$1" --all-databases > backup.sql
+
+# # Check if the dump was successful
+# if [ $? -ne 0 ]; then
+#   echo "MySQL dump failed!"
+#   exit 1
+# fi
+
+# # Compress the dump file to a tar.gz archive with the format day-month-year.tar.gz
+# tar -cvzf "$(date +"%d-%m-%Y").tar.gz" backup.sql
+
+# # Check if the compression was successful
+# if [ $? -ne 0 ]; then
+#   echo "Compression failed!"
+#   exit 1
+# fi
+
+# # Remove the original dump file to save space
+# rm backup.sql
+
+# echo "Backup and compression completed successfully."
